---
- include: kvm_install_check.yml

- name: "Install KVM packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - qemu-kvm
    - qemu-utils
    - libvirt-bin
    - python3-libvirt
    - python3-lxml
    - ebtables
    - dnsmasq-base
  register: apt_kvm

- name: Restart Libvirt service
  service:
    name: libvirtd
    state: restarted
  when: apt_kvm.changed
