---
- include: kvm_install_check.yml

- name: "Install KVM packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - qemu-kvm
    - libvirt-bin
    - python3-libvirt
    - python3-lxml
